import re

def parse_markdown(file_path):
    with open(file_path, 'r') as f:
        lines = f.readlines()

    title = ""
    bio = ""
    links = []
    
    parsing_links = False
    
    for line in lines:
        line = line.strip()
        if not line:
            continue
            
        if line.startswith("# ") and not title:
            title = line[2:].strip()
        elif line.startswith("## Links"):
            parsing_links = True
        elif parsing_links and line.startswith("- "):
            # Parse link format: - [Title](url) - Description
            match = re.match(r'- \[(.*?)\]\((.*?)\) - (.*)', line)
            if match:
                link_title, link_url, link_desc = match.groups()
                links.append({
                    'title': link_title,
                    'url': link_url,
                    'desc': link_desc
                })
        elif not parsing_links and not bio and not line.startswith("#"):
            bio = line

    return title, bio, links

def generate_html(title, bio, links, template_path, output_path):
    with open(template_path, 'r') as f:
        template = f.read()

    links_html = ""
    for link in links:
        links_html += f"""
                <li>
                    <a href="{link['url']}" class="link-item">
                        <span class="link-title">{link['title']}</span>
                        <span class="link-desc">{link['desc']}</span>
                    </a>
                </li>"""

    html = template.replace('{{ title }}', title)
    html = html.replace('{{ bio }}', bio)
    html = html.replace('{{ links }}', links_html)

    with open(output_path, 'w') as f:
        f.write("<!-- This file is auto-generated by build.py. Edits will be overwritten. -->\n")
        f.write(html)
    
    print(f"Successfully generated {output_path}")

if __name__ == "__main__":
    title, bio, links = parse_markdown("content.md")
    generate_html(title, bio, links, "template.html", "index.html")
